version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: ${POSTGRES_DB:-system_database}
    secrets:
      - postgres_user
      - postgres_password
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:latest
    volumes:
      - ./db-init:/flyway/sql
      - ./flyway/entrypoint.sh:/flyway/entrypoint.sh:ro
    entrypoint: ["sh", "/flyway/entrypoint.sh"]
    depends_on:
      - postgres
    secrets:
      - postgres_user
      - postgres_password

  keycloak:
    build: ./keycloak
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-system_database}?currentSchema=keycloak
      KC_DB_USERNAME_FILE: /run/secrets/postgres_user
      KC_DB_PASSWORD_FILE: /run/secrets/postgres_password
      KC_DB_SCHEMA: keycloak
      KEYCLOAK_ADMIN_FILE: /run/secrets/keycloak_admin
      KEYCLOAK_ADMIN_PASSWORD_FILE: /run/secrets/keycloak_password
    volumes:
      - ./keycloak/keycloak-realm.json:/opt/keycloak/data/import/keycloak-realm.json:ro
      - ./keycloak/realm-t1.json:/opt/keycloak/data/import/realm-t1.json:ro
      - ./keycloak/realm-t2.json:/opt/keycloak/data/import/realm-t2.json:ro
    secrets:
      - postgres_user
      - postgres_password
      - keycloak_admin
      - keycloak_password
    depends_on:
      - postgres
      - flyway
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5

  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - osdata:/usr/share/opensearch/data
      - ./opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    environment:
      SERVER_BASEPATH: /dashboards
      SERVER_REWRITEBASEPATH: "true"
      OPENSEARCH_HOSTS: '["http://opensearch:${OPENSEARCH_PORT:-9200}"]'
    volumes:
      - ./opensearch-dashboards/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml:ro
    depends_on:
      - opensearch
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/api/status"]
      interval: 30s
      timeout: 10s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.route-prefix=/prometheus'
      - '--web.external-url=http://localhost/prometheus'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/ready"]
      interval: 30s
      timeout: 10s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
      - postgres
    restart: unless-stopped
    environment:
      GF_SERVER_ROOT_URL: "http://localhost/grafana"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      GF_DATABASE_TYPE: "postgres"
      GF_DATABASE_HOST: "postgres:${POSTGRES_PORT:-5432}"
      GF_DATABASE_NAME: ${POSTGRES_DB:-system_database}
      GF_DATABASE_USER_FILE: /run/secrets/postgres_user
      GF_DATABASE_PASSWORD_FILE: /run/secrets/postgres_password
      GF_DATABASE_SSL_MODE: "disable"
      GF_DATABASE_SCHEMA: "grafana"
      GF_SECURITY_ADMIN_PASSWORD_FILE: /run/secrets/grafana_password
    secrets:
      - postgres_user
      - postgres_password
      - grafana_password
    volumes:
      - grafana-storage:/var/lib/grafana
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  status:
    build: ./status
    ports:
      - "${STATUS_PORT:-3001}:3001"
    depends_on:
      - postgres
      - keycloak
      - opensearch
      - opensearch-dashboards
      - prometheus
      - grafana
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/online"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://user:pass@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-system_database}?sslmode=disable&search_path=app
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/home"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build: ./frontend
    depends_on:
      - keycloak
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  typesense:
    image: typesense/typesense:0.24.1
    command: ["--data-dir", "/data", "--api-key", "${TYPESENSE_API_KEY:-secret}"]
    volumes:
      - typesense-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8108/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  filegator:
    image: filegator/filegator:latest
    depends_on:
      - typesense
    volumes:
      - filegator-data:/var/www/filegator/repository
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongodb:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 30s
      timeout: 10s
      retries: 5

  outline:
    image: outlinewiki/outline:latest
    environment:
      DATABASE_URL: postgres://user:pass@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-system_database}
      DATABASE_SSL: "false"
      REDIS_URL: redis://redis:6379
      SECRET_KEY_FILE: /run/secrets/outline_secret_key
      UTILS_SECRET_FILE: /run/secrets/outline_utils_secret
      URL: http://localhost/outline
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY:-secret}
      TYPESENSE_NODES: '[{"host":"typesense","port":8108,"protocol":"http"}]'
    depends_on:
      - postgres
      - redis
      - typesense
    secrets:
      - outline_secret_key
      - outline_utils_secret
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  answer:
    image: answerdev/answer:latest
    environment:
      DB_TYPE: postgresql
      DB_DSN: postgres://user:pass@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-system_database}?sslmode=disable
      TYPESENSE_ENDPOINT: http://typesense:8108
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY:-secret}
    depends_on:
      - postgres
      - typesense
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  metabase:
    image: metabase/metabase:latest
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${POSTGRES_DB:-system_database}
      MB_DB_PORT: ${POSTGRES_PORT:-5432}
      MB_DB_USER_FILE: /run/secrets/postgres_user
      MB_DB_PASS_FILE: /run/secrets/postgres_password
      MB_DB_HOST: postgres
    secrets:
      - postgres_user
      - postgres_password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  formio:
    image: formio/formio:latest
    restart: unless-stopped
    environment:
      MONGO: mongodb://mongodb:27017/formio
      PORT: 3001
    volumes:
      - ./formio/formio.yml:/data/formio.yml:ro
    depends_on:
      - mongodb
    ports:
      - "${FORMIO_PORT:-3005}:3001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${NGINX_PORT:-80}:80"
    restart: unless-stopped
    depends_on:
      - status
      - grafana
      - opensearch-dashboards
      - keycloak
      - prometheus
      - opensearch
      - filegator
      - outline
      - answer
      - metabase
      - typesense
      - formio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pgdata:
  osdata:
  grafana-storage:
  typesense-data:
  filegator-data:
  mongodb-data:

secrets:
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  keycloak_admin:
    file: ./secrets/keycloak_admin.txt
  keycloak_password:
    file: ./secrets/keycloak_password.txt
  grafana_password:
    file: ./secrets/grafana_password.txt
  outline_secret_key:
    file: ./secrets/outline_secret_key.txt
  outline_utils_secret:
    file: ./secrets/outline_utils_secret.txt
